data_cfg:
  dataset_name: Gait3D
  dataset_root: /data/lxl/Gaitdata/Gait3D-pkls/Gait3D-sils-64-44-pkl/
  dataset_partition: ./datasets/Gait3D/Gait3D.json
  num_workers: 4
  remove_no_gallery: false
  test_dataset_name: Gait3D

evaluator_cfg:
  enable_float16: true
  restore_ckpt_strict: true
  restore_hint: 'output/OUMVLP/GaitSet/GaitSet/checkpoints/GaitSet-250000.pt'
  save_name: Baseline
  eval_func: evaluate_Gait3D
  sampler:
    batch_shuffle: false
    batch_size: 16
    sample_type: all_ordered # all indicates whole sequence used to test, while ordered means input sequence by its natural order; Other options:   fixed_unordered
    frames_all_limit: 720 # limit the number of sampled frames to prevent out of memory
  metric: euc # cos euc
  transform:
    - type: BaseSilCuttingTransform

loss_cfg:
  loss_term_weight: 1.0
  margin: 0.2
  type: TripletLoss
  log_prefix: triplet

model_cfg:
  model: GaitSet
  in_channels:
    - 1
    - 64
    - 128
    - 256
  SeparateFCs:
    in_channels: 256
    out_channels: 256
    parts_num: 62
  bin_num:
    - 16
    - 8
    - 4
    - 2
    - 1

optimizer_cfg:
  lr: 0.0001
  momentum: 0.9
  solver: Adam
  weight_decay: 0

scheduler_cfg:
  gamma: 0.1
  milestones:
    - 150000
  scheduler: MultiStepLR

trainer_cfg:
  enable_float16: true # half_percesion float for memory reduction and speedup
  fix_BN: false
  log_iter: 100
  with_test: true
  restore_ckpt_strict: true
  restore_hint: 'output/OUMVLP/GaitSet/GaitSet/checkpoints/GaitSet-250000.pt'
  save_iter: 10000
  save_name: Baseline
  sync_BN: true
  total_iter: 60000
  sampler:
    batch_shuffle: true
    batch_size:
      - 8 # TripletSampler, batch_size[0] indicates Number of Identity
      - 4 #                 batch_size[1] indicates Samples sequqnce for each Identity
    frames_num_fixed: 30 # fixed frames number for training
    frames_num_max: 50 # max frames number for unfixed training
    frames_num_min: 25 # min frames number for unfixed traing
    sample_type: fixed_unordered # fixed control input frames number, unordered for controlling order of input tensor; Other options: unfixed_ordered or all_ordered
    type: TripletSampler
  transform:
    - type: BaseSilCuttingTransform
