# Note  : *** the batch_size should be equal to the gpus number at the test phase!!! ***
data_cfg:
  dataset_name: Gait3D
  dataset_root: /data/lxl/Gaitdata/Gait3D-pkls/Gait3D-sils-64-44-pkl/
  dataset_partition: ./datasets/Gait3D/Gait3D.json
  num_workers: 1
  remove_no_gallery: false
  test_dataset_name: Gait3D

evaluator_cfg:
  enable_float16: true
  restore_ckpt_strict: true
  restore_hint: 60000
  save_name: GaitBase_DA
  eval_func: evaluate_Gait3D
  sampler:
    batch_shuffle: false
    batch_size: 1
    sample_type: all_ordered # all indicates whole sequence used to test, while ordered means input sequence by its natural order; Other options:   fixed_unordered
    frames_all_limit: 720
    type: InferenceSampler
  metric: euc # cos
  transform:
    - type: BaseSilCuttingTransform

inference_cfg:
  enable_float16: true
  restore_ckpt_strict: true
  restore_hint: ./output/OUMVLP/GaitGL/GaitGL/checkpoints/GaitGL-210000.pt
  save_name: GaitBase_DA
  eval_func: evaluate_Gait3D
  sampler:
    batch_shuffle: true
    batch_size: 1
    frames_num_fixed: 30 # fixed frames number for training
    frames_num_max: 50 # max frames number for unfixed training
    frames_num_min: 10 # min frames number for unfixed traing
    sample_type: fixed_unordered
    frames_all_limit: 720
    type: InferenceSampler
    # limit the number of sampled frames to prevent out of memory
    metric: euc # cos
#  transform:
#    - type: Compose
#      trf_cfg:
#        - type: RandomPerspective
#          prob: 0.2
#        - type: BaseSilCuttingTransform
#        - type: RandomHorizontalFlip
#          prob: 0.2
#        - type: RandomRotate
#          prob: 0.2


loss_cfg:
  - loss_term_weight: 1.0
    margin: 0.2
    type: TripletLoss
    log_prefix: triplet
  - loss_term_weight: 1.0
    scale: 1
    type: CrossEntropyLoss
    log_accuracy: true
    label_smooth: true
    log_prefix: softmax

model_cfg:
  model: GaitGL
  channels: [32, 64, 128, 256]
  class_num: 5153

optimizer_cfg:
  lr: 1.0e-4
  solver: Adam
  weight_decay: 0

scheduler_cfg:
  gamma: 0.1
  milestones:
    - 150000
    - 200000
  scheduler: MultiStepLR

trainer_cfg:
  enable_float16: true # half_percesion float for memory reduction and speedup
  fix_BN: false
  with_test: true
  log_iter: 100
  restore_ckpt_strict: true
  restore_hint: ./output/OUMVLP/GaitGL/GaitGL/checkpoints/GaitGL-210000.pt
  save_iter: 20000
  save_name: GaitBase_DA
  sync_BN: true
  total_iter: 60000
  sampler:
    batch_shuffle: true
    batch_size:
      - 16 # TripletSampler, batch_size[0] indicates Number of Identity
      - 4 #                 batch_size[1] indicates Samples sequqnce for each Identity
    frames_num_fixed: 30 # fixed frames number for training
    frames_num_max: 50 # max frames number for unfixed training
    frames_num_min: 10 # min frames number for unfixed traing
    sample_type: fixed_unordered # fixed control input frames number, unordered for controlling order of input tensor; Other options: unfixed_ordered or all_ordered
    type: TripletSampler
#  transform:
#    - type: Compose
#      trf_cfg:
#        - type: RandomPerspective
#          prob: 0.2
#        - type: BaseSilCuttingTransform
#        - type: RandomHorizontalFlip
#          prob: 0.2
#        - type: RandomRotate
#          prob: 0.2

